### ISSUE TITLE
Investigate an example GridFTP plugin

### ISSUE THREAD

**Issue by ray-millward-tessella** [ral-facilities/gridftp_acl_plugin#2]
We need to first understand how a GridFTP plugin is written, built and integrated. We should look for an example of a plugin on the web as well as talk to anyone else in SCD who has written a plugin for GridFTP.

Acceptance criteria:
- Find an example GridFTP plugin codebase.
- Understand and document the fundamental structure of a plugin.
- Understand and document the build and deployment process for a plugin.
- Understand and document how calls to the plugin work once deployed.

**Comment by daniel-hunt-tessella** [comment]
There are now links to several examples of gridftp plugins in the [documentation](https://github.com/ral-facilities/gridftp_acl_plugin/wiki/gridftp-plugin-structure)

We have demonstrated the ability to write and build a basic plugin and this is documented in the same place.

The documentation includes details of what deploying a gridftp plugin looks like and has an example inplementation on how we are going to make calls to the plugin work once deployed.

Further work to understand these processes and document them will naturally follow as part of #4 and #5
