### ISSUE TITLE
Investigate the development process for working with GridFTP

### ISSUE THREAD

**Issue by ray-millward-tessella** [ral-facilities/gridftp_acl_plugin#3]
In order to have a rapid dev/test cycle we need to work out how to have a gridFTP instance we can each work with as a developer. This may involve working out how to provision an instance locally or it may mean working out how to provision them in the OpenStack cloud.

It may turn out that the interface is fairly standard and we just need to be concerned with making sure the code does the right thing. This may minimise integration with the full GridFTP node.

Acceptance Criteria:
- work out how to deploy a plugin in progress so we can test in GridFTP.
- demonstrate updating a plugin in GridFTP

**Comment by conor-proud-tessella** [comment]
Useful resources for deciding what needs to be overwritten:
http://toolkit.globus.org/api/c-globus-6.0/files.html
http://toolkit.globus.org/api/c-globus-6.0/globus__gridftp__server_8h_source.html    (see lines ~779)

**Comment by daniel-hunt-tessella** [comment]
The setting up a dev environment wiki page contains details of how to deploy a plugin. The process of updating a plugin is as simple as changing the code and then using ninja to rebuild the plugin. This is quick and easy to do (does not require re-provisioning or anything prohibitively time-consuming).

This process has been demonstrated by Conor
