### ISSUE TITLE
Write a gridftp plugin that simply logs when called

### ISSUE THREAD

**Issue by ray-millward-tessella** [ral-facilities/gridftp_acl_plugin#4]
The first step in creating the plugin is to create a simple plugin that logs when called.

Acceptance Criteria:
- Have a plugin that can be called using GridFTP that simply logs to a file when called.

**Comment by daniel-hunt-tessella** [comment]
Testing Steps:

1. Build the code (including re-provisioning)
2. From the build folder run ../run-gridftp-server.sh to start the server.
3. Open a second cmd prompt, login using vagrant ssh machine1 to the same machine
4. Copy and paste the ftpClient script from the demos folder into the build folder
5. Run the ftpClient script (python ftpClient.py) to test calling the SITE GETPERMISSIONS command
6. Stop the gridftp server
7. Look at the logs in /usr/tmp/gridftp_acl_plugin.log - it will look something like [this](https://github.com/ral-facilities/gridftp_acl_plugin/files/2530655/GET.PERMISSIONS.log.example.txt)

Following these steps and getting such a log message shows that the plugin can create log messages when the SITE GETPERMISSIONS command is called
